### ISSUE TITLE
使用shift打开的preview里面内容是空的

### ISSUE THREAD

**Issue by gggin** [xfslove/alfred-google-translate#11]
![default](https://user-images.githubusercontent.com/3293064/43184769-4b10b1e8-901c-11e8-9ffd-e661ddc54d4b.png)

我曾经修改过按回车打开url 但是不久以后会被npm给覆盖
我想增加一个按2下alt就弹出被选中的翻译弹出功能，是否可以提PR

**Comment by xfslove** [comment]
我没太明白你的需求

**Comment by xfslove** [comment]
@gggin 你好，我没太明白你的需求

1.  shift打开是白色可能是网络原因
2.  显示不出来的话，可以试一下cmd+y

**Comment by gggin** [comment]
先说两下alt， 连续按两下alt可以弹出翻译 然后自动翻译被选中的问题（这个很简单，不用写代码），直接加个Hotkey就可以了

我看了alfred，但是我不知道作者你是如何实现出preview的，但是我吧quicklookurl里面的东西直接放到浏览器里面是可以打开的（未翻墙)，我其实只想要一个可以打开google translate网页把翻译内容显示的功能，但是不知道为什么{var:quicklookurl}在我这里就是不好使。

**Comment by xfslove** [comment]
实际这个{var:quicklookurl}是没用的，quicklookurl需要的参数再index.js中已经定义好了，并需要额外的参数

你可以在workflow中把Open URL删掉再重新创建一个，试一下

关于这个quicklookurl，alfred文档原文

**Comment by xfslove** [comment]
@gggin 实际这个{var:quicklookurl}是没用的，quicklookurl需要的参数再index.js中已经定义好了，并需要额外的参数

你可以在workflow中把Open URL删掉再重新创建一个，试一下

关于这个quicklookurl，alfred[文档原文](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/)

```
A Quick Look URL which will be visible if the user uses the Quick Look feature within Alfred (tapping shift, or cmd+y). Note that quicklookurl will also accept a file path, both absolute and relative to home using ~/.

```

最后你说的按两下alt弹出翻译，这个我觉得可能有点重复，而且使用起来并没有quicklook方便，你习惯的话可以自己在workflow中定义一下hotkey自己使用😀
