### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by szweee** [xfslove/alfred-google-translate#14]
npm ERR! Darwin 17.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "alfred-google-translate"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yanjiaying/npm-debug.log

**Comment by xfslove** [comment]
@szweee 你`node_modules`权限有点问题，看信息`Please try running this command again as root/Administrator.`

**Comment by szweee** [comment]
还是不行  

> alfred-google-translate@1.1.0 postinstall /usr/local/lib/node_modules/alfred-google-translate
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/yanjiaying/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:15:10)

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-google-translate/node_modules/execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/yanjiaying/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:15:10)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! Darwin 17.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "alfred-google-translate"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! alfred-google-translate@1.1.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfred-google-translate@1.1.0 postinstall script 'alfy-init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alfred-google-translate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     alfy-init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alfred-google-translate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alfred-google-translate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yanjiaying/npm-debug.log

**Comment by szweee** [comment]
在github上直接下载安装的也翻译报错
<img width="1225" alt="2018-10-17 4 44 02" src="https://user-images.githubusercontent.com/20777870/47073970-017a8200-d22c-11e8-86c9-72035a7a991d.png">

**Comment by xfslove** [comment]
related #13

**Comment by xfslove** [comment]
这个问题应该是alfred的问题，不是workflow的问题，先关闭了
