### ISSUE TITLE
一直显示翻译中

### ISSUE THREAD

**Issue by liyangpro** [xfslove/alfred-google-translate#17]
![image](https://user-images.githubusercontent.com/9484545/49367263-7e06e880-f726-11e8-9afe-6bd61c5f8684.png)

**Comment by xfslove** [comment]
@liyangpro 麻烦把workflow的版本贴出来一下

**Comment by liyangpro** [comment]
版本是v1.1.1
现在也报了403
![image](https://user-images.githubusercontent.com/9484545/49414803-9c64f680-f7af-11e8-842a-1e6232280dc3.png)
和 #16 一样的情况。

**Comment by xfslove** [comment]
@liyangpro 是直接下载的workflow，还是npm安装的

**Comment by liyangpro** [comment]
直接下载的
![image](https://user-images.githubusercontent.com/9484545/49416151-fd8ec900-f7b3-11e8-8614-0e3b09a9cc2f.png)

**Comment by xfslove** [comment]
@lingyv token获取的方式似乎又变了，[看这儿](https://github.com/vitalets/google-translate-token/blob/845f830ea1c2f5839f91cfd1d4335fc0e624787b/index.js#L84)，我不清楚这个是不是会经常变，能否有个方式能及时得到这个修改

**Comment by xfslove** [comment]
@onlyless 感谢反馈，也麻烦试一下新的版本

**Comment by onlyless** [comment]
@xfslove 新版本我这里用着没问题，就是新版本翻译时把输入也当成了输出
![image](https://user-images.githubusercontent.com/24915490/49579380-05529700-f987-11e8-9db9-4adb7277faa9.png)

**Comment by xfslove** [comment]
@onlyless 嗯，新版加入了显示音标，会显示查询内容的音标和翻译结果的音标，如图：
<img width="840" alt="1" src="https://user-images.githubusercontent.com/7803346/49621514-a9c4ef80-fa00-11e8-9218-cc921d0ab6d7.png">
不过由于接口内容的限制，有的内容拿不到音标，所以就无法显现，比如你输入的`hello world`🙂

关于更新内容可以看下[这里](https://github.com/xfslove/alfred-google-translate/releases)

**Comment by liyangpro** [comment]
@xfslove 新版本可以用了。不过就是有点慢。
尤其是查完英文 -> 中文后，再使用 中文 -> 英文的时候大约有10秒左右的延迟。我本地的梯子速度还是比较快，暂时不清楚是哪里的问题。

**Comment by xfslove** [comment]
@liyangpro 现在的workflow是不需要梯子的，可能是新版加了下载语音的功能，这个地方比较慢，后面再优化一下，可选下载语音还是用本地语音
