### ISSUE TITLE
如果是Shadowsock.如何配置让其支持sock5代理方式？

### ISSUE THREAD

**Issue by Hansoncoder** [xfslove/alfred-google-translate#2]
现在都流行用SS来FQ上网，如果是SS，怎么配置代理来支持这个翻译？

**Comment by xfslove** [comment]
@Hansoncoder 抱歉，目前并不支持sock5，不过如果是用的Shadowsocks，是带有http 代理的

如图：
<img width="480" alt="1" src="https://user-images.githubusercontent.com/7803346/38651306-168fe8ac-3e33-11e8-8423-0106dffd1510.png">

Shadowsocks默认使用[privoxy](http://www.privoxy.org)将sock5转成http的，如果Shadowsocks版本不支持也可以自己配置一个
