### ISSUE TITLE
建议：希望增加保留查询历史记录的功能

### ISSUE THREAD

**Issue by likecreep** [xfslove/alfred-google-translate#20]
保留查询历史记录到一个本地文档。

**Comment by suboyang** [comment]
不知道什么原因，我如果是大段落复制，只能翻译第一句话，字数太多就不能翻译了，不知道什么原因，希望改进，大段落的翻译是一个常用的功能，期待更新。

**Comment by suboyang** [comment]
这个功能很重要。

**Comment by xfslove** [comment]
> 这个功能很重要。

有兴趣PR吗🙂

**Comment by suboyang** [comment]
倒是有兴趣
工作有点忙

Sent from my iPhone

On Mar 18, 2019, at 9:04 AM, Iven <notifications@github.com<mailto:notifications@github.com>> wrote:


这个功能很重要。

有兴趣PR吗🙂

**Comment by xfslove** [comment]
采集一下有多少人需要这个功能。

**Comment by suboyang** [comment]
我个人认为，你这个代码是很有创意的模块，尤其对于mac 阅读pdf文档,不用来回切换桌面，查看浏览器，但是估计不会超过万人，比较大量阅读英文文档的人，就是非常小众的人群。

Sent from my iPhone

On Mar 19, 2019, at 11:39 AM, Iven <notifications@github.com<mailto:notifications@github.com>> wrote:


采集一下有多少人需要这个功能。

**Comment by suboyang** [comment]
我个人认为历史记录还好，我个人感觉用处不大。但是如果能设置语言翻译对应，那么你的用户群就是来自全世界的了！

Sent from my iPhone

On Mar 19, 2019, at 11:39 AM, Iven <notifications@github.com<mailto:notifications@github.com>> wrote:


采集一下有多少人需要这个功能。

**Comment by suboyang** [comment]
我个人觉得先让全世界的极客都能用的你设计的模块，后面的bug都好说

Sent from my iPhone

On Mar 19, 2019, at 11:39 AM, Iven <notifications@github.com<mailto:notifications@github.com>> wrote:


采集一下有多少人需要这个功能。

**Comment by xfslove** [comment]
> 我个人觉得先让全世界的极客都能用的你设计的模块，后面的bug都好说
> […](#)

感谢给出的建议

**Comment by xfslove** [comment]
Please upgrade to v2.x
