### ISSUE TITLE
大段落翻译无法实现

### ISSUE THREAD

**Issue by suboyang** [xfslove/alfred-google-translate#23]
我画了大段落的文字，但只能翻译第一句话。您能帮我解决吗 ？怎么样可以画大段落复制，而直接翻译出来。

![](https://user-images.githubusercontent.com/4099914/54426965-1c5a0f80-4754-11e9-9890-a4d1794f9a66.png)

**Comment by suboyang** [comment]
![image](https://user-images.githubusercontent.com/4099914/54425521-7bb62080-4750-11e9-9ec8-0d236b9a672f.png)

![image](https://user-images.githubusercontent.com/4099914/54425550-8c669680-4750-11e9-931f-a86d1b23b683.png)

**Comment by suboyang** [comment]
![image](https://user-images.githubusercontent.com/4099914/54426965-1c5a0f80-4754-11e9-9890-a4d1794f9a66.png)

**Comment by suboyang** [comment]
实在是谢谢了，感觉你这个功能可以逆天，我主要想解决大段文字处理的问题，不用在网页里来回转帖。

**Comment by suboyang** [comment]
我又用了几次，发现你的问题是，文章的之间的标点是有空格的，而你的$1参数把这些空格看成了参数的间隔符，并没有把后面的内容算进去，所以只能翻译头一句话。希望你解决这个问题。

**Comment by xfslove** [comment]
> 我又用了几次，发现你的问题是，文章的之间的标点是有空格的，而你的$1参数把这些空格看成了参数的间隔符，并没有把后面的内容算进去，而只能翻译一句话。所以你的解决方法很简单，只要多加几个$2 $3 $4....这样的参数，把文章所有的句子识别出来，一般情况下，一段话也就顶多10句话。这样很好解决这个问题了。

我看看
