### ISSUE TITLE
发音问题

### ISSUE THREAD

**Issue by suboyang** [xfslove/alfred-google-translate#24]
发现你的发音功能在单词上是可以的，但是如果是整句话，或者整段话，就无法发音了。请修复bug。

还有你的cmd+l功能，既然shift 是快照，那么为啥不用shift+l 这样更方便记忆？
或者你能不把shift 本身就改成cmd+l功能，这样不更好用 ？

**Comment by xfslove** [comment]
关于快捷键的问题，cmd+L是workflow默认的largetype的快捷键
