### ISSUE TITLE
翻译基础设置功能

### ISSUE THREAD

**Issue by suboyang** [xfslove/alfred-google-translate#25]
我也用了其他的google translate, 我个人认为你的模块缺少一个google translate 基础设置功能，就是把哪种语言翻译成哪种对应的语言。
这里有一个很好的例子，你可以借鉴一下。
https://github.com/DONSA/alfred-google-translate

我个人认为如果你能把这个基础设置功能结合进来，并把大段落翻译，和发音问题解决，你这个翻译模块趋向完美。

**Comment by xfslove** [comment]
采集一下有多少人需要这个功能

**Comment by suboyang** [comment]
_对于我现在的应用，我觉得应该没什么问题了，但是如果加了基础功能的模块，我认为你的用户群会扩大到全世界，而不只是中国的工程师和翻译人员，那个时候会有更多人提建议和bug。模块更完善。

**Comment by xfslove** [comment]
> _对于我现在的应用，我觉得应该没什么问题了，但是如果加了基础功能的模块，我认为你的用户群会扩大到全世界，而不只是中国的工程师和翻译人员，那个时候会有更多人提建议和bug。模块更完善。

感谢给出的建议

**Comment by xfslove** [comment]
relate #29
