### ISSUE TITLE
大段落翻译仍有问题，63个单词以上，无法翻译。

### ISSUE THREAD

**Issue by suboyang** [xfslove/alfred-google-translate#26]
今天学习的时候发现，只要单词超过63个，workflow就没有反应了。需要修复bug. 
举例如下。
Although Botswana’s economic outlook remains strong, the devastation that AIDS has caused threatens to destroy the country’s future. In 2001, Botswana has the highest rate of HIV infection in the world. With the help of international donors it launched an ambitious national campaign that provided free antiviral drugs to anyone who needed them, and by March 2004, Botswana’s infection rate has dropped significantly.

**Comment by xfslove** [comment]
看了一下，tts-api一次字符长度不能超过200。空了修复一下

**Comment by suboyang** [comment]
感觉63个词实在是太少了，一段文字，怎么也得200个词吧。
不过仍然感谢你的回复，期待你的好消息。

**Comment by suboyang** [comment]
我也查到了这个信息 https://github.com/zlargon/google-tts，是不是可以用来解决
multiple URLs，可能代码改的地方比较多，比如先要计算到底有多少字符，用总数/200， 
取余，然后发起多个multiple URLs连接，最后把返回的值整合。 
思路应该是这么个思路，不知道你没有时间改了。
