### ISSUE TITLE
Run with error.

### ISSUE THREAD

**Issue by vfptr** [xfslove/alfred-google-translate#27]
Error in the console:
[ERROR: input.scriptfilter] Code 1: /Users/Matthew/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/alfred-google-translate/index.js:65
          const [text, relation] = x;
                ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

node version:
         v5.9.0
->     v11.14.0
         system
default -> node (-> v11.14.0)
node -> stable (-> v11.14.0) (default)
stable -> 11.14 (-> v11.14.0) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.16.0 (-> N/A)
lts/dubnium -> v10.15.3 (-> N/A)

**Comment by xfslove** [comment]
麻烦贴一下翻译报错的单词

**Comment by vfptr** [comment]
随便输一个单词就报错，比如“what"

**Comment by xfslove** [comment]
@vfptr  我看了一下你报错的位置，这行代码是老版本的，你使用的`alfred-google-translate`版本似乎不是最新版的(最新是1.1.8)，麻烦更新到最新版再试一下

**Comment by vfptr** [comment]
更新后还是类似的问题，日志如下：
[ERROR: input.scriptfilter] Code 1: /Users/Matthew/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.F87909B9-0D67-49F9-A3B3-AA79B7AFFC89/index.js:101
          const [explain, nvl, example] = m;
                ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

环境如下：
[Matthew@rmbp] user.workflow.F87909B9-0D67-49F9-A3B3-AA79B7AFFC89$ node -v
v11.14.0
[Matthew@rmbp] user.workflow.F87909B9-0D67-49F9-A3B3-AA79B7AFFC89$ npm -g ls|grep google
├─┬ alfred-google-translate@1.1.8

**Comment by xfslove** [comment]
@vfptr 你电脑上是有多个node版本吗？看起来好像是workflow使用的node版本不支持destructuring

**Comment by vfptr** [comment]
我使用nvm管理的版本，另外还有一个5.9不在使用中，昨天郁闷之下我把5.9给删了，只留了一个最新的node11.x，然后居然问题解决了。
很奇怪的问题，5.9好像也支持destructuring的吧。

**Comment by xfslove** [comment]
@vfptr  v6之前好像需要--harmony_destructuring才支持destructuring。

我先把这个issue关闭了
