### ISSUE TITLE
加了代理还是不能用

### ISSUE THREAD

**Issue by hungry0** [xfslove/alfred-google-translate#3]

**Comment by xfslove** [comment]
@hungry0 需要workflow的环境变量里配置了代理地址

**Comment by hungry0** [comment]
![image](https://user-images.githubusercontent.com/13111009/39854008-1d60c7f6-5458-11e8-95b1-688bf34bea25.png)
是指这个吗，确实配了的

**Comment by xfslove** [comment]
@hungry0 确定1087端口是http代理端口吗？

如果是用的Shadowsocks有如图的配置：
<img width="480" alt="qq20180510-174500 2x" src="https://user-images.githubusercontent.com/7803346/39863720-0b1ff0b8-547a-11e8-9d62-ebe6ba74b70e.png">

或者可以把你的配置贴出来

**Comment by hungry0** [comment]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/13111009/39867541-f33cd5d4-5487-11e8-9f71-f5250e2b073e.png">
请问是这样吗

**Comment by xfslove** [comment]
@hungry0  这个地方确实是这样配置的，但是要确保1087端口是http代理端口

你可以看看是否有`privoxy`进程，或者Shadowsocks配置是否也正确
