### ISSUE TITLE
alfred 4 npm安装失败

### ISSUE THREAD

**Issue by sp0cket** [xfslove/alfred-google-translate#31]
```
Error: Command failed: alfred-link
Error: Workflow directory `/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows` does not exist
    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/alfred-link/index.js:19:10

    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/execa/index.js:201:11
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Workflow directory ' +
    '`/Users/xxx/Library/Application Support/Alfred ' +
    '3/Alfred.alfredpreferences/workflows` does not exist\n    ' +
    'at ' +
    '/usr/local/lib/node_modules/alfred-google-translate/node_modules/alfred-link/index.js:19:10\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false
}
```

看报错还是在使用alfred3的目录

**Comment by xfslove** [comment]
npm 安装使用的是alfy，好像暂时还 不支持alfred 4，[看这里](https://github.com/sindresorhus/alfy/issues/110)，你可以试试直接下载安装包安装

**Comment by ifyour** [comment]
@xfslove 如何手动安装呢？自己打包成 `*.alfredworkflow` 文件？

**Comment by xfslove** [comment]
@ifyour 直接下载就行，[下载地址](https://github.com/xfslove/alfred-google-translate/releases/tag/v2.0.1)

**Comment by ifyour** [comment]
@xfslove Thanks，我意思是想自己构建一版，不过目前 Alfy 暂时不支持 Alfred 4，不能手动导出 `*. alfredworkflow` 文件。

**Comment by LitoMore** [comment]
Hi there! Now Alfy supports Alfred 4, alfred-link has been released a patch update to add support for Alfred 4. Just update your dependencies to get it to work. 😄

**Comment by xfslove** [comment]
> Hi there! Now Alfy supports Alfred 4, alfred-link has been released a patch update to add support for Alfred 4. Just update your dependencies to get it to work. 😄

thx, its awesome! ill work on it.

**Comment by xfslove** [comment]
could rerun `npm install -g alfred-google-translate` to get it to work.

**Comment by sp0cket** [comment]
是不是close早了，当前release版本v2.0.5使用npm安装还是会报这个错

**Comment by sp0cket** [comment]
目前alfy版本是0.9.0建议新开个v3分支升级下相关依赖以兼容alfred4，当前v2版本可以继续维护

**Comment by xfslove** [comment]
> 目前alfy版本是0.9.0建议新开个v3分支升级下相关依赖以兼容alfred4，当前v2版本可以继续维护

我刚看了一下我自己的，我还是安到了alfred 3的目录下，以为成功了，我更新一下，非常感谢反馈🙂

**Comment by xfslove** [comment]
@sp0cket 我更新了alfy的版本，你可以再试一下是否能用npm安装成功🙂

**Comment by sp0cket** [comment]
npm安装目前没有报错，但是翻译时有报错

```
ERROR: Google Translate[Script Filter] JSON error: Garbage at end. in JSON:
...
"quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=auto&tl=en&text=test",
			"arg": "/var/folders/4s/w36m9w555jq8qjkh3ytvxjgh0000gn/T/7dea6e12-6501-4a17-8154-185b64056d6e.mp3",
...
"title": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=4&q=test&tk=697416.786675\n    at /Users/sp0cket/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/alfred-google-translate/node_modules/got/index.js:123:13\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)",
			"text": {
				"copy": "```\nHTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=4&q=test&tk=697416.786675\n    at /Users/sp0cket/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/alfred-google-translate/node_modules/got/index.js:123:13\n```\n\n-\nGoogle Translate 2.0.6\nAlfred 4.0.3\ndarwin 18.7.0",
				"largetype": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=4&q=test&tk=697416.786675\n    at /Users/sp0cket/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/alfred-google-translate/node_modules/got/index.js:123:13"
			},
```

**Comment by xfslove** [comment]
> npm安装目前没有报错，但是翻译时有报错
> 
> ```
> ERROR: Google Translate[Script Filter] JSON error: Garbage at end. in JSON:
> ...
> "quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=auto&tl=en&text=test",
> 			"arg": "/var/folders/4s/w36m9w555jq8qjkh3ytvxjgh0000gn/T/7dea6e12-6501-4a17-8154-185b64056d6e.mp3",
> ...
> "title": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=4&q=test&tk=697416.786675\n    at /Users/sp0cket/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/alfred-google-translate/node_modules/got/index.js:123:13\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)",
> 			"text": {
> 				"copy": "```\nHTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=4&q=test&tk=697416.786675\n    at /Users/sp0cket/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/alfred-google-translate/node_modules/got/index.js:123:13\n```\n\n-\nGoogle Translate 2.0.6\nAlfred 4.0.3\ndarwin 18.7.0",
> 				"largetype": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=4&q=test&tk=697416.786675\n    at /Users/sp0cket/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/alfred-google-translate/node_modules/got/index.js:123:13"
> 			},
> ```

@sp0cket 你应该是没有配置吧，看一下alfred-language-configuration

**Comment by sp0cket** [comment]
`alfred-language-configuration`这个库npm安装的时候页报了alfy这个问题

**Comment by xfslove** [comment]
> `alfred-language-configuration`这个库npm安装的时候也报了alfy这个问题

😅我忘记更新那个workflow了，等会儿我更新一下

**Comment by xfslove** [comment]
@sp0cket 已经更新好了，可以试一试

**Comment by sp0cket** [comment]
看起来都没问题了，thx
