### ISSUE TITLE
一直显示翻译中，提示输入错误

### ISSUE THREAD

**Issue by JusticeGO** [xfslove/alfred-google-translate#35]
大佬求帮助~npm安装，v2.0.1
![image](https://user-images.githubusercontent.com/41421539/60880718-c0714480-a276-11e9-9b22-f27af15cc31a.png)

RequestError: connect ETIMEDOUT 88.191.249.182:443
Url: https://translate.google.cn/translate_a/single?client=t&sl=en&tl=zh-CN&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=good&tk=629764.983966
    at ClientRequest.req.once.err (/Users/gongz/.nvm/versions/node/v10.11.0/lib/node_modules/alfred-google-translate/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by JusticeGO** [comment]
node version:
->     v10.11.0
         system
default -> stable (-> v10.11.0)
node -> stable (-> v10.11.0) (default)
stable -> 10.11 (-> v10.11.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.4 (-> N/A)
lts/carbon -> v8.12.0 (-> N/A)

**Comment by lonelygo** [comment]
看说明，新版本要装一个alfred-language-configuration的插件，先配置翻译语言和目标语言，貌似不支持自动检测语言了。

**Comment by JusticeGO** [comment]
> 看说明，新版本要装一个alfred-language-configuration的插件，先配置翻译语言和目标语言，貌似不支持自动检测语言了。

alfred-language-configuration我已经装了

**Comment by lonelygo** [comment]
有点奇怪啊，你报错的Url，正常返回了txt。
要么就是nvm的锅？
我是直接下载装的，没有用npm。

**Comment by xfslove** [comment]
看你的错误好像是超时了，你看下你环境变量有配置domain=https://translate.google.cn吗

**Comment by JusticeGO** [comment]
> 看你的错误好像是超时了，你看下你环境变量有配置domain=[https://translate.google.cn吗](https://translate.google.cn%E5%90%97)

有的，三个环境变量都设置了，很奇怪啊
Aflred v3.8.2 [963]
<img width="485" alt="屏幕快照 2019-07-10 10 04 54" src="https://user-images.githubusercontent.com/41421539/60934813-497d8f80-a2fa-11e9-9f72-78c4f0bcaa20.png">

**Comment by JusticeGO** [comment]
好了...改成system的node就能用了....
<img width="389" alt="屏幕快照 2019-07-10 16 01 56" src="https://user-images.githubusercontent.com/41421539/60951653-2cfa4b00-a32c-11e9-82ab-4c1e80e62a8e.png">

**Comment by lonelygo** [comment]
> 好了...改成system的node就能用了....
> <img alt="屏幕快照 2019-07-10 16 01 56" width="389" src="https://user-images.githubusercontent.com/41421539/60951653-2cfa4b00-a32c-11e9-82ab-4c1e80e62a8e.png">

恭喜成功让nvm接锅🤣

**Comment by JusticeGO** [comment]
> > 好了...改成system的node就能用了....
> > <img alt="屏幕快照 2019-07-10 16 01 56" width="389" src="https://user-images.githubusercontent.com/41421539/60951653-2cfa4b00-a32c-11e9-82ab-4c1e80e62a8e.png">
> 
> 恭喜成功让nvm接锅🤣

哈哈哈哈😂
