### ISSUE TITLE
shift 无法打开网页

### ISSUE THREAD

**Issue by it-noob** [xfslove/alfred-google-translate#37]
安装方式：根据文档提示 npm 安装和直接下载安装包，都发生如下情况

选中结果点击 shift，也没有打开网页，而是如下的空白

<img width="607" alt="屏幕快照 2019-07-25 11 20 32" src="https://user-images.githubusercontent.com/12043442/61843454-3d82f780-aece-11e9-8f81-2b55ad2d680c.png">

**Comment by xfslove** [comment]
麻烦提供一下是在哪个具体选项上不能打开网页。

如果是在相关翻译[Translations]选项上是没有打开网页的。

如果是其它选项上，麻烦提供一下alfred、chrome版本，或者点一下’open with google chrome‘，看一下网址

**Comment by it-noob** [comment]
@xfslove 

<img width="588" alt="屏幕快照 2019-07-26 12 09 08" src="https://user-images.githubusercontent.com/12043442/61925287-34f9f200-af9e-11e9-82b8-975f8040581d.png">


结果里所有的选项按 `shift` 都是那个 Chrome截图的效果

alfred 版本是：v3.5.1[883]

Chrome 版本是：75.0.3770.142

请求地址
```
https://translate.google.cn/#view=home&op=translate&sl=zh-CN&tl=en&text=%E7%8E%B0%E9%87%91
```

**Comment by xfslove** [comment]
这个问题似乎不是workflow的问题，不知道是不是alfred版本问题，我再查查

**Comment by xfslove** [comment]
@it-noob 看下你macOS的版本是10.12吗，如果是的话，这个一个macOS bug，你可以看下[这个](https://www.alfredforum.com/topic/11413-lost-ability-to-quicklook-urls-in-macos-1012-bug-in-macos-sierra/)

**Comment by it-noob** [comment]
非常感谢回复，竟然遇到了 macOS 的 bug，确认是这个 bug，回头我升级系统版本吧
