### ISSUE TITLE
如何切换英译中和中译英呢

### ISSUE THREAD

**Issue by LuckyDogg** [xfslove/alfred-google-translate#39]
![image](https://user-images.githubusercontent.com/16526987/62011005-2c273d00-b1a5-11e9-8eeb-c43527e13805.png)

**Comment by xfslove** [comment]
看下主页说明，2.x版本需要[alfred-language-configuration](https://github.com/xfslove/alfred-language-configuration)

**Comment by xfslove** [comment]
@LuckyDogg 新的版本（2.0.3）已经支持语言自动检测了，可以更新到新版试用。

这个issue我就先关闭了，如果试用中还有问题可以再打开🙂
