### ISSUE TITLE
`shift` 不工作

### ISSUE THREAD

**Issue by kelly-apollo** [xfslove/alfred-google-translate#4]
`shift` 不工作，没有获取到当前查询的单词，Google translate 的 URL 更新了？

![image](https://user-images.githubusercontent.com/4319332/41084451-d31fc65e-6a66-11e8-871e-95356bf26965.png)

**Comment by xfslove** [comment]
@kelly-apollo 确实是URL变了，我已经改成了新的URL，更新下就行
