### ISSUE TITLE
throw an error that "Couldn't find the `node` binary"

### ISSUE THREAD

**Issue by mingzhaocn** [xfslove/alfred-google-translate#40]
My node is installed using nvm.
the path is ~/.nvm/versions/node/v12.8.1/bin/node

**Comment by xfslove** [comment]
have you specified which the node OS uses? like `nvm use ***`.

please make sure the `node -v` 'll print the node version.

**Comment by mingzhaocn** [comment]
> have you specified which the node OS uses? like `nvm use ***`.
> 
> please make sure the `node -v` 'll print the node version.

I am sure node is available.

The good news it works after reinstallation.

Thanks
