### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by zbl-96** [xfslove/alfred-google-translate#42]
[14:34:43.543] Logging Started...
[14:34:56.692] Google Translate[Script Filter] Queuing argument 'goo'
[14:34:57.242] Google Translate[Script Filter] Queuing argument 'google'
[14:35:04.274] Google Translate[Script Filter] Script with argument 'google' finished
[14:35:04.278] ERROR: Google Translate[Script Filter] Code 1: {
	"items": [
		{
			"title": "google",
			"subtitle": "Phonetic: ˈgo͞ogəl",
			"quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=auto&tl=en&text=google",
			"arg": "/var/folders/fv/jbxz4v8944l5z47y3mc52h600000gn/T/5a946a2a-2242-4656-9b7a-c0456e3daaa8.mp3",
			"text": {
				"copy": "google",
				"largetype": "google"
			},
			"icon": {
				"path": "tts.png"
			}
		},
		{
			"title": "google",
			"subtitle": "Phonetic: ",
			"quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=en&tl=auto&text=google",
			"arg": "/var/folders/fv/jbxz4v8944l5z47y3mc52h600000gn/T/8304a186-edab-4570-92c2-9de707684d9e.mp3",
			"text": {
				"copy": "google",
				"largetype": "google"
			},
			"icon": {
				"path": "tts.png"
			}
		},
		{
			"title": "Definition[动词]: search for information about (someone or something) on the Internet using the search engine Google.",
			"subtitle": "Example: I recently googled my 7th grade teacher and found his current e-mail address",
			"quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=auto&tl=en&text=google",
			"text": {
				"copy": "search for information about (someone or something) on the Internet using the search engine Google.",
				"largetype": "Definitions: search for information about (someone or something) on the Internet using the search engine Google.\n\nExample: I recently googled my 7th grade teacher and found his current e-mail address"
			}
		}
	]
}
{
	"items": [
		{
			"title": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=6&q=google&tk=734758.889464\n    at /Users/zbl/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6B6BE3E4-03F9-4C9A-A9A9-68C305B7A59F/node_modules/got/index.js:123:13\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nHTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=6&q=google&tk=734758.889464\n    at /Users/zbl/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6B6BE3E4-03F9-4C9A-A9A9-68C305B7A59F/node_modules/got/index.js:123:13\n```\n\n-\nGoogle Translate 2.0.5\nAlfred 4.0.1\ndarwin x64 19.0.0",
				"largetype": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=6&q=google&tk=734758.889464\n    at /Users/zbl/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6B6BE3E4-03F9-4C9A-A9A9-68C305B7A59F/node_modules/got/index.js:123:13"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[14:35:04.320] ERROR: Google Translate[Script Filter] JSON error: Garbage at end. in JSON:
{
	"items": [
		{
			"title": "google",
			"subtitle": "Phonetic: ˈgo͞ogəl",
			"quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=auto&tl=en&text=google",
			"arg": "/var/folders/fv/jbxz4v8944l5z47y3mc52h600000gn/T/5a946a2a-2242-4656-9b7a-c0456e3daaa8.mp3",
			"text": {
				"copy": "google",
				"largetype": "google"
			},
			"icon": {
				"path": "tts.png"
			}
		},
		{
			"title": "google",
			"subtitle": "Phonetic: ",
			"quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=en&tl=auto&text=google",
			"arg": "/var/folders/fv/jbxz4v8944l5z47y3mc52h600000gn/T/8304a186-edab-4570-92c2-9de707684d9e.mp3",
			"text": {
				"copy": "google",
				"largetype": "google"
			},
			"icon": {
				"path": "tts.png"
			}
		},
		{
			"title": "Definition[动词]: search for information about (someone or something) on the Internet using the search engine Google.",
			"subtitle": "Example: I recently googled my 7th grade teacher and found his current e-mail address",
			"quicklookurl": "https://translate.google.cn/#view=home&op=translate&sl=auto&tl=en&text=google",
			"text": {
				"copy": "search for information about (someone or something) on the Internet using the search engine Google.",
				"largetype": "Definitions: search for information about (someone or something) on the Internet using the search engine Google.\n\nExample: I recently googled my 7th grade teacher and found his current e-mail address"
			}
		}
	]
}
{
	"items": [
		{
			"title": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=6&q=google&tk=734758.889464\n    at /Users/zbl/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6B6BE3E4-03F9-4C9A-A9A9-68C305B7A59F/node_modules/got/index.js:123:13\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nHTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=6&q=google&tk=734758.889464\n    at /Users/zbl/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6B6BE3E4-03F9-4C9A-A9A9-68C305B7A59F/node_modules/got/index.js:123:13\n```\n\n-\nGoogle Translate 2.0.5\nAlfred 4.0.1\ndarwin x64 19.0.0",
				"largetype": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.cn/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=6&q=google&tk=734758.889464\n    at /Users/zbl/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6B6BE3E4-03F9-4C9A-A9A9-68C305B7A59F/node_modules/got/index.js:123:13"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}

macos 10.15
alfred 4.0.1
alfred-google-translate:2.0.5

**Comment by xfslove** [comment]
it seems like youare not config the language pairs. please see [alfred-language-configuraiton](https://github.com/xfslove/alfred-language-configuration)

**Comment by xfslove** [comment]
hi @zbl-96 , I'll close this issue. and if you got the same error again. you could reopen it.🙂

**Comment by zbl-96** [comment]
@xfslove  正常工作了 非常感谢.
