### ISSUE TITLE
显示一直翻译中，ss挂了全局代理

### ISSUE THREAD

**Issue by mercer08** [xfslove/alfred-google-translate#43]
![image](https://user-images.githubusercontent.com/12872293/64142016-dcd7ca80-ce3c-11e9-8c77-c83358f41d52.png)
![image](https://user-images.githubusercontent.com/12872293/64142047-fbd65c80-ce3c-11e9-9840-7772c1b6d85d.png)
![image](https://user-images.githubusercontent.com/12872293/64142052-01cc3d80-ce3d-11e9-9ebf-bab5152b3b3a.png)

**Comment by mercer08** [comment]
安装方式是通过下载workflow安装

**Comment by mercer08** [comment]
![image](https://user-images.githubusercontent.com/12872293/64142091-27594700-ce3d-11e9-8918-06637dfa45ff.png)

**Comment by xfslove** [comment]
看一下readme。需要配置一个domain https://translate.google.cn

**Comment by mercer08** [comment]
> 看一下readme。需要配置一个domain https://translate.google.cn
> 
> 现在取消配置代理了

解决了，非常感谢！
