### ISSUE TITLE
JSON error: Garbage at end. in JSON errors

### ISSUE THREAD

**Issue by zajako** [xfslove/alfred-google-translate#46]
[01:31:35.879] ERROR: Google Translate[Script Filter] JSON error: Garbage at end. in JSON:
{
	"items": [
		{
			"title": "무기 타격치",
			"subtitle": "Phonetic: mugi tagyeogchi",
			"quicklookurl": "https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%E1%84%86%E1%85%AE%E1%84%80%E1%85%B5%20%E1%84%90%E1%85%A1%E1%84%80%E1%85%A7%E1%86%A8%E1%84%8E%E1%85%B5",
			"arg": "/var/folders/n3/0qlv7v8n1hvd6mml886wzzbr0000gn/T/c45944ce-ad5b-462d-994b-43b4fd65dabe.mp3",
			"text": {
				"copy": "무기 타격치",
				"largetype": "무기 타격치"
			},
			"icon": {
				"path": "tts.png"
			}
		},
		{
			"title": "Weapons tagyeokchi",
			"subtitle": "Phonetic: ",
			"quicklookurl": "https://translate.google.com/#view=home&op=translate&sl=en&tl=auto&text=Weapons%20tagyeokchi",
			"arg": "/var/folders/n3/0qlv7v8n1hvd6mml886wzzbr0000gn/T/a8eda803-6801-4376-9998-8e5d9ee4f4a3.mp3",
			"text": {
				"copy": "Weapons tagyeokchi",
				"largetype": "Weapons tagyeokchi"
			},
			"icon": {
				"path": "tts.png"
			}
		}
	]
}
{
	"items": [
		{
			"title": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.com/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=12&q=%E1%84%86%E1%85%AE%E1%84%80%E1%85%B5%20%E1%84%90%E1%85%A1%E1%84%80%E1%85%A7%E1%86%A8%E1%84%8E%E1%85%B5&tk=597562.1030535\n    at stream.catch.then.data (/Users/zajako/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.83B28437-DDBE-4680-9B18-D1FF690AC29F/node_modules/got/index.js:123:13)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nHTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.com/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=12&q=%E1%84%86%E1%85%AE%E1%84%80%E1%85%B5%20%E1%84%90%E1%85%A1%E1%84%80%E1%85%A7%E1%86%A8%E1%84%8E%E1%85%B5&tk=597562.1030535\n    at stream.catch.then.data (/Users/zajako/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.83B28437-DDBE-4680-9B18-D1FF690AC29F/node_modules/got/index.js:123:13)\n    at <anonymous>\n```\n\n-\nGoogle Translate 2.0.6\nAlfred 4.0.4\ndarwin 18.7.0",
				"largetype": "HTTPError: Response code 404 (Not Found)\nUrl: https://translate.google.com/translate_tts?client=t&tl=auto&ie=UTF-8&idx=0&total=1&textlen=12&q=%E1%84%86%E1%85%AE%E1%84%80%E1%85%B5%20%E1%84%90%E1%85%A1%E1%84%80%E1%85%A7%E1%86%A8%E1%84%8E%E1%85%B5&tk=597562.1030535\n    at stream.catch.then.data (/Users/zajako/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.83B28437-DDBE-4680-9B18-D1FF690AC29F/node_modules/got/index.js:123:13)\n    at <anonymous>"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}

**Comment by xfslove** [comment]
Before using this workflow, You must config the language pair. see [alfred-language-configuration](https://github.com/xfslove/alfred-language-configuration)
