### ISSUE TITLE
不规范的字符应该是给建议不是报错

### ISSUE THREAD

**Issue by shaodahong** [xfslove/alfred-google-translate#49]
![image](https://user-images.githubusercontent.com/14831261/67390298-f8ef2100-f5ce-11e9-9e7c-c5160a0517c7.png)

**Comment by xfslove** [comment]
这个是因为workflow把`mentio`语言检测成Latin，我看看这种情况怎么优化一下吧

**Comment by xfslove** [comment]
新版如果检测到输入语言不是配置的语言会给提示

The latest version will prompt you if detected the input language is not the configured language.

**Comment by shaodahong** [comment]
应该和1.x版本一样纠错

**Comment by shaodahong** [comment]
已经设置了默认的
![image](https://user-images.githubusercontent.com/14831261/67449526-08ad4a80-f64d-11e9-8714-f17934138d3a.png)

**Comment by xfslove** [comment]
@shaodahong 纠错一直都有的

不过这个单词太特特殊了，google翻译检测出来是拉丁语

官网翻译结果如下：
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/7803346/67449701-9b4de980-f64d-11e9-9931-efde7db9a872.png">

**Comment by xfslove** [comment]
我觉得workflow的和官网的表达y应该尽量差不多，@shaodahong 觉得呢？

**Comment by shaodahong** [comment]
说实话整体体验下来还是 1.x 版本顺手，可能是之前用习惯了……

**Comment by xfslove** [comment]
@shaodahong  感谢一直的支持，确实，如果只是中英互译的话，1.x就行了，简单很多

2.x 要兼容所有语言，所以难免会复杂，会多一些步骤，但只要有人提出建议，肯定也会慢慢不断地优化下去🙂
