### ISSUE TITLE
获取不到Selection in macOS

### ISSUE THREAD

**Issue by SpringHerald** [xfslove/alfred-google-translate#50]
选中一些文本，按快捷键后弹出的框中没有内容。
这个是debug输出的日志
```
[15:58:56.549] Google Translate[Hotkey] Processing complete
[15:58:56.553] Google Translate[Hotkey] Passing output '' to Script Filter
```
但是如果选项改成macOS clipboard contents就能用，弹出的框中就有内容。

macOS 10.14.6, node v12.12，Alfred 4.0.6破解版

**Comment by xfslove** [comment]
这个应该不是workflow的问题，感觉会不会是和你其它软件冲突了

**Comment by SpringHerald** [comment]
找到解决方法了：https://www.alfredforum.com/topic/11711-alfred-37-beta-for-mojave-beta-4/

quit Alfred then open the macOS Security & Privacy > Accessibility preferences. Remove both Alfred 3 and Alfred Text Service, then restart your Mac.

**Comment by luoluoluo22** [comment]
我按照题主的办法尝试，没有找到 alfred3，重启也没有成功，后来发现是我的安装包问题，我安装的是 alfred4.1.1（1171）汉化版，其中的功能有缺陷，就是不能从 macos 中获取内容。重新下载英文原版就可以了。推荐下载链接: https://pan.baidu.com/s/1DTX1U_FA-xgXEHtUzKZhwQ  密码: 1234

**Comment by Jancd** [comment]
> 我按照题主的办法尝试，没有找到 alfred3，重启也没有成功，后来发现是我的安装包问题，我安装的是 alfred4.1.1（1171）汉化版，其中的功能有缺陷，就是不能从 macos 中获取内容。重新下载英文原版（已破解）就可以了。推荐下载链接: https://pan.baidu.com/s/1DTX1U_FA-xgXEHtUzKZhwQ 密码: 1234

你这提取码也不对撒....
