### ISSUE TITLE
不能直接按住热键之后 直接翻译我在屏幕上划词的内容吗

### ISSUE THREAD

**Issue by Garlichead** [xfslove/alfred-google-translate#56]
不能直接按住热键之后 直接翻译我在屏幕上划词的内容吗 这样就不要做重复工作 先打开翻译 再把划词内容复制进去 还是我不会用？

**Comment by xfslove** [comment]
如果你是下载的安装包，可能是没有配置热键[看看这个](https://github.com/xfslove/alfred-google-translate#environment-variables-config-snapshot)

**Comment by Garlichead** [comment]
> 如果你是下载的安装包，可能是没有配置热键[看看这个](https://github.com/xfslove/alfred-google-translate#hotkey)

我设置打开翻译的启动键是option+t 但是我按opthon+t 可以打开翻译试图 但是无法直接翻译我在屏幕上划词的内容 还需要我手动复制需要翻译的内容 然后粘贴到翻译框里面

**Comment by xfslove** [comment]
你看下是不是没给Alfred权限 #50

**Comment by xfslove** [comment]
如果没有问题我就先把这个issue关闭了，有问题可以再开
