### ISSUE TITLE
cmd+c 复制内容的具体代码逻辑实现在？

### ISSUE THREAD

**Issue by Garlichead** [xfslove/alfred-google-translate#57]
我查看了源码 cmd+c 复制内容的具体代码逻辑实现在？我想增加一个扩展 就是我想用cmd+x键将查词同步到我的anki单词本

**Comment by xfslove** [comment]
[代码在这儿](https://github.com/xfslove/alfred-google-translate/blob/f6dbadbcd2b7e55424b463730d3f42de1e93db48/index.js#L139)，快捷键是script json format默认的

**Comment by Garlichead** [comment]
> [代码在这儿](https://github.com/xfslove/alfred-google-translate/blob/f6dbadbcd2b7e55424b463730d3f42de1e93db48/index.js#L139)，快捷键是[script filter json format](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/)默认的

我其实想增加一个扩展 我按cmd+x之后 或者enter键之后 能执行我某一个代码块 我的代码快里面有实现同步anki接口的逻辑 但是我刚刚看了你这边使用快捷键默认处理之后 不是很理解

**Comment by Garlichead** [comment]
其实我就是想增加一个监听 按住cmd+x或者其他快捷键 执行我的代码块逻辑 代码块里面可以拿到翻译的所有结果

**Comment by xfslove** [comment]
如果要加一个你所说的功能，我目前想到的可能需要加一个类似这个workflow中发音的Bash Script。
<img width="660" alt="1" src="https://user-images.githubusercontent.com/7803346/75863696-dc47dd00-5e3b-11ea-809b-b939f719305b.png">

**Comment by Garlichead** [comment]
> Bash Script

Bash Script中可以不知道是否可以调用anki的接口 anki目前开放的接口有python版本的javascript版本

**Comment by xfslove** [comment]
python应该可以，你可以试试

**Comment by xfslove** [comment]
这个issue我先关闭了，如果有好的实现欢迎PR!
