### ISSUE TITLE
Selection in MacOS don't work

### ISSUE THREAD

**Issue by AleksIralda** [xfslove/alfred-google-translate#63]
I try use hotkey for fast translate but not working, in log I just see
"Passing output '' to Script Filter". But Using "MacOS Clipboard Contents" Works!
 
Any can help with this?
Thnks

<img width="540" alt="Screen Shot 2020-05-07 at 21 46 13" src="https://user-images.githubusercontent.com/10256929/81365030-b2659d80-90ac-11ea-8ad3-a46bc17a81a8.png">

**Comment by xfslove** [comment]
it maybe caused by your Alfred doesnt has the Accessibility privacy. please have a check.

**Comment by AleksIralda** [comment]
I had already checked Alfred on Accessibility Privacy Menu, but I re-check again and now works! Thnks!!

**Comment by Garlichead** [comment]
haha, If you find that it is still unavailable, you need to click to cancel and reselect it. Just tested.

**Comment by 8ku** [comment]
> haha, If you find that it is still unavailable, you need to click to cancel and reselect it. Just tested.

It worked, thank you!!
