### ISSUE TITLE
Workflow doesn't

### ISSUE THREAD

**Issue by dhd80** [xfslove/alfred-google-translate#64]
Hi, I tried this workflow and it's properly installed, but if I type for example 'tr car', I only see 'Detected your input language is Englisch, not one of your Configuration' and nothing happens. Thanks in advance and greetings

**Comment by xfslove** [comment]
please see the [installation](https://github.com/xfslove/alfred-google-translate#installation), you need install alfred-language-configuration too.

**Comment by xfslove** [comment]
I'll close this issue. you could reopen it or create a new one if you have any questions.
