### ISSUE TITLE
Translation not showing

### ISSUE THREAD

**Issue by pbdco** [xfslove/alfred-google-translate#69]
Done install from npm install -g alfred-google-translate and made trc en&es but when I write is keeps on "Translating.."

![image](https://user-images.githubusercontent.com/64397076/85206007-689be400-b2f5-11ea-97cf-6659fead7c26.png)

**Comment by xfslove** [comment]
please make sure you can access the https://translate.google.com. or configure the environment variable set the domain you can access. like https://translate.google.cn.

**Comment by pbdco** [comment]
set https://translate.google.com on value but not working either

**Comment by xfslove** [comment]
> set https://translate.google.com on value but not working either

Are you sure you can access the translate.google.com without any proxies?

**Comment by pbdco** [comment]
> > set https://translate.google.com on value but not working either
> 
> Are you sure you can access the translate.google.com without any proxies?

Yes, I can access normally

**Comment by xfslove** [comment]
its weird. please have try with translate.google.es.

**Comment by pbdco** [comment]
Not working either. Tried install/uninstall several times manually and from terminal and nothing.

**Comment by xfslove** [comment]
please open your alfred debug mode, and post it. I'll take a look.

**Comment by pbdco** [comment]
[2:10:59.599] Google Translate[Script Filter] Queuing argument 'hola'

![image](https://user-images.githubusercontent.com/64397076/85953803-48999f80-b949-11ea-9a90-152d6a370fb3.png)

**Comment by xfslove** [comment]
It seems like network issue. 

could you please replace the workflow's translate.js file with [translate.js.zip](https://github.com/xfslove/alfred-google-translate/files/4843403/translate.js.zip) (I handled the timeout error). and post the logging again.

the translate.js file location: ~/Application\ Support/Alfred/Alfred.alfredpreferences/workflows/alfred-google-translate/translate.js

**Comment by pbdco** [comment]
I opened Alfred.alfredpreferences >show contents but I don't have such folder. 

![image](https://user-images.githubusercontent.com/64397076/86149624-9d1c5680-bad2-11ea-862c-19a8a56f3056.png)

![image](https://user-images.githubusercontent.com/64397076/86149546-78c07a00-bad2-11ea-9eed-b7192d876ad1.png)

**Comment by xfslove** [comment]
you could do like this:
<img width="1101" alt="1" src="https://user-images.githubusercontent.com/7803346/86218931-0de76f80-bbb4-11ea-95f2-1d0c8e5f41ca.png">

**Comment by pbdco** [comment]
Hi, this is working now. It was my internet connection issue not related to alfred or your workflow. My appologies, thank you for your support and your great workflow. Regards
