### ISSUE TITLE
刚刚调试了一下 我看到这里有一个步骤耗时是最多的 有10s

### ISSUE THREAD

**Issue by Garlichead** [xfslove/alfred-google-translate#70]
![image](https://user-images.githubusercontent.com/45086633/90301251-5ee7c480-ded1-11ea-99ba-e944f86838a2.png)
确认一直受到翻译慢的问题困扰～

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/90301912-39f55080-ded5-11ea-8d45-1ce550f41c4e.png)
所以我还是在代码中更改了网络设置 这样我的翻译就只有1s中时间了

**Comment by Garlichead** [comment]
使用 https://translate.google.com 站点 不使用 cn站点

**Comment by xfslove** [comment]
做个PR吧。注意一下看加了代理会不会影响没有代理软件的伙伴使用后OK。

**Comment by Garlichead** [comment]
> 做个PR吧。注意一下，加了代理别影响没有代理软件的伙伴使用后OK。

老哥 我现在还是很慢 原因被我发现了 这里面使用node请求google翻译 翻译请求并没有被我的vpn surge进行代理 所以一直导致网络翻译不出来 之前可以翻译 是因为我surge开了增强模式 但是增强模式我不能一直开 和公司内网vpn冲突了

**Comment by Garlichead** [comment]
老铁 这个翻译耽误我太多时间了 想放弃使用了 我现在surge死活不能代理这个tcp的node请求
但是你的cn域名访问也太慢了 根本无法接受le

**Comment by xfslove** [comment]
需要socks-proxy-agent。我空了看下
relate: #44

**Comment by Garlichead** [comment]
> 需要socks-proxy-agent。我空了看下
> relate: #44

您好 socks-proxy-agent 这个怎么配置？ 我是使用surge
进行代理我的网络

**Comment by Garlichead** [comment]
我的surge现在只能代理http协议 如果要代理node的tcp 需要开启增强模式 但是增强模式和我们公司内网的vpn冲突了

**Comment by Garlichead** [comment]
https://www.npmjs.com/package/socks-proxy-agent <https://www.npmjs.com/package/socks-proxy-agent>
这个站点这样修改代码吗

**Comment by Garlichead** [comment]
老铁 你这个node 使用的是什么请求方式 是否可以设置请求走代理 我查了一下资料 node请求可以设置走proxy代理 配置代理服务器就好了
