### ISSUE TITLE
早上翻译突然提示429？？ 是不是验证接口出问题了

### ISSUE THREAD

**Issue by Garlichead** [xfslove/alfred-google-translate#71]
![image](https://user-images.githubusercontent.com/45086633/92191213-ba382180-ee95-11ea-86ce-3d92f3fb232d.png)
突然出现的 无网络问题

**Comment by xfslove** [comment]
这个问题一直都没有很好得解决，https://github.com/xfslove/alfred-google-translate/issues/45

Garlichead <notifications@github.com> 于2020年9月4日周五 上午10:02写道：

**Comment by Garlichead** [comment]
今天第一次遇到 使用这么久了 第一次遇到

**Comment by xfslove** [comment]
relate #45
