### ISSUE TITLE
dialogflow

### ISSUE THREAD

**Issue by thehallow** [xfslove/alfred-google-translate#72]
Hej!
i am trying to connect dialogflow with google translate Api but it does not work:

const translate = new Translate();
translate('Tu es incroyable',{to:'en'}).then( response=>{
            agent.add(response.text);
        }).catch(error=>{
            agent.add("error");
        });
i am using dialogflow inline editor. is there any way to do it? thank you for helping

**Comment by xfslove** [comment]
please raise an issue at https://github.com/vitalets/google-translate-api.
