### ISSUE TITLE
我使用时总是提示not one of your configuration

### ISSUE THREAD

**Issue by wupuyuan** [xfslove/alfred-google-translate#78]
如题：
not one of your configuration 
代码中是判断didYouMean那里，返回的总是false。
是安装后，需要配置什么吗？
form language 是auto
我的alfred是4.3.2

**Comment by xfslove** [comment]
需要安装alfred-language-configration

**Comment by xfslove** [comment]
我先把这个issue关闭了，如果有问题可以这个issue重新开
