### ISSUE TITLE
突然间response code 429

### ISSUE THREAD

**Issue by kathy330** [xfslove/alfred-google-translate#80]
参数设置
![image](https://user-images.githubusercontent.com/39319724/111905337-3c3d1000-8a9f-11eb-8917-106abcb45f76.png)
突然之间tr word就变成了response code 429， 这要怎么解决？
![image](https://user-images.githubusercontent.com/39319724/111905383-7ad2ca80-8a9f-11eb-918f-89a34f940b1f.png)

**Comment by xfslove** [comment]
这个只能试着换代理试试 #45

**Comment by xfslove** [comment]
这个issue先关闭了，后续相关问题解决方法会同步在置顶issue
