### ISSUE TITLE
Alfred 3 安装后显示不可用

### ISSUE THREAD

**Issue by EchoZhaoH** [xfslove/alfred-google-translate#83]
![image](https://user-images.githubusercontent.com/23427655/124404978-c3bd3f00-dd6f-11eb-9d55-438b6ce8aeee.png)

![image](https://user-images.githubusercontent.com/23427655/124404967-b86a1380-dd6f-11eb-9579-0fc76027c8b0.png)

**Comment by xfslove** [comment]
你alfred什么版本，需要alfred版本3或4

**Comment by EchoZhaoH** [comment]
@xfslove 我的 Alfred 版本是 3 的最新版

**Comment by EchoZhaoH** [comment]
@xfslove 上面的截图上有

**Comment by EchoZhaoH** [comment]
还有人解决吗 @xfslove

**Comment by xfslove** [comment]
> 还有人解决吗 @xfslove

不好意思，最近太忙了，可能回复不及时，你电脑上有安装node吗

**Comment by EchoZhaoH** [comment]
@xfslove 嗯嗯 有的

**Comment by xfslove** [comment]
> @xfslove 嗯嗯 有的

你是通过命令行安装的是吧，如果是命令行安装的是只能是alfred4，如果是alfred3可以下载包

**Comment by EchoZhaoH** [comment]
@xfslove 哦哦 好的 谢谢
